apiVersion: v2
name: ruby-on-rails
description: |
  A getting started helm chart for running a ruby-on-rails application.

  This chart runs a kubernetes deployment, service and migration job.

type: application
version: 0.0.3
