image:
  repository:
  tag:

command: ["bundle"]
args: ["exec", "rails", "server"]

envs: []
port:

serviceAccount:
  annotations: {}
  name:

resourceRequests: {}
resourceLimits: {}

replicas:
  autoscalingEnabled: false
  replicaCount:
  minReplicas:
  maxReplicas:
  targetCPUUtilizationPercentage:

ingress:
  annotations: {}
  enabled: true
  className:
  host:
  path:

commonLabels: {}

pod:
  annotations: {}

migration:
  enabled: true
  command: ["bash", "-c"]
  args:
    - bundle exec rails db:create;
      bundle exec rails db:migrate;

massdriver-alarm-channel:
  enabled: false