completions:
parallelism:

image:
  repository:
  tag:

command: []
args: []

envs: []

serviceAccount:
  annotations: {}
  name:

resourceRequests: {}
resourceLimits: {}

labels: {}

# nodeSelector: {}

# tolerations: []

# affinity: {}