apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "massdriver.fullname" . }}-massdriver
  labels:
    {{- include "massdriver.labels" . | nindent 4 }}
    app.kubernetes.io/component: massdriver
spec:
  replicas: {{ .Values.massdriver.replicaCount }}
  selector:
    matchLabels:
      {{- include "massdriver.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: massdriver
  template:
    metadata:
      {{- with .Values.massdriver.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "massdriver.labels" . | nindent 8 }}
        {{- with .Values.massdriver.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        app.kubernetes.io/component: massdriver
    spec:
      imagePullSecrets:
        - name: {{ include "massdriver.fullname" . }}-dockerhub
      serviceAccountName: {{ include "massdriver.fullname" . }}-massdriver
      {{- with .Values.massdriver.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: massdriver
          image: "{{ .Values.massdriver.image.repository }}:{{ .Values.massdriver.image.tag }}"
          imagePullPolicy: {{ .Values.massdriver.image.pullPolicy }}
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          envFrom:
            - configMapRef:
                name: {{ include "massdriver.fullname" . }}-massdriver-envs
            - secretRef:
                name: {{ include "massdriver.fullname" . }}-massdriver-envs
            {{- if and .Values.minio.enabled (eq .Values.massdriver.blobStorage.type "minio") }}
            - secretRef:
                name: {{ include "massdriver.fullname" . }}-massdriver-minio-auth
            {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.massdriver.port }}
              protocol: TCP
            {{- if .Values.massdriver.epmd.enabled }}
            - name: epmd
              containerPort: {{ .Values.massdriver.epmd.port }}
              protocol: TCP
            {{- end }}
          {{- with .Values.massdriver.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.massdriver.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.massdriver.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.massdriver.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        - name: ui
          image: "{{ .Values.ui.image.repository }}:{{ .Values.ui.image.tag }}"
          imagePullPolicy: {{ .Values.ui.image.pullPolicy }}
          ports:
            - name: ui
              containerPort: {{ .Values.ui.port }}
              protocol: TCP
          {{- with .Values.ui.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.ui.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.ui.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.ui.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: ui
              mountPath: /app/.env
              subPath: env
      volumes:
        - name: ui
          configMap:
            name: {{ include "massdriver.fullname" . }}-ui
      {{- with .Values.massdriver.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.massdriver.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.massdriver.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
