{{- if and .Values.massdriver.ingress.tls.createSecret .Values.massdriver.ingress.tls.cert .Values.massdriver.ingress.tls.key }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "massdriver.tlsSecretName" . }}
  labels:
    {{- include "massdriver.labels" . | nindent 4 }}
    app.kubernetes.io/component: massdriver
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.massdriver.ingress.tls.cert | b64enc }}
  tls.key: {{ .Values.massdriver.ingress.tls.key | b64enc }}
{{- end }}