apiVersion: v1
kind: Secret
metadata: 
  name: {{ include "massdriver.fullname" . }}-dockerhub
  labels:
    {{- include "massdriver.labels" . | nindent 4 }}
    app.kubernetes.io/component: massdriver
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{
    printf "{\"auths\":{\"https://index.docker.io/v1/\":{\"username\":\"%s\",\"password\":\"%s\",\"auth\":\"%s\"}}}"
      .Values.dockerhub.username
      .Values.dockerhub.accessToken
      (printf "%s:%s" .Values.dockerhub.username .Values.dockerhub.accessToken | b64enc)
    | b64enc
  }}
