apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "massdriver.fullname" . }}-provisioner
  labels:
    {{- include "massdriver.labels" . | nindent 4 }}
    app.kubernetes.io/component: provisioner
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "massdriver.fullname" . }}-argo-workflows-workflow
subjects:
- kind: ServiceAccount
  name: {{ include "massdriver.fullname" . }}-provisioner
  namespace: {{ .Release.Namespace }}