{{- if .Values.massdriver.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "massdriver.fullname" . }}-provisioner
  labels:
    {{- include "massdriver.labels" . | nindent 4 }}
    app.kubernetes.io/component: provisioner
  {{- with .Values.provisioner.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.provisioner.serviceAccount.automount }}
{{- end }}
