{{- if and .Values.aws.securityGroup.enabled .Values.aws.securityGroup.id -}}
{{- $securityGroupId := .Values.aws.securityGroup.id -}}
apiVersion: vpcresources.k8s.aws/v1beta1
kind: SecurityGroupPolicy
metadata:
  name: {{ include "application.fullname" . }}
  labels:
    {{- include "application.labels" . | nindent 4 }}
spec:
  podSelector: 
    matchLabels:
      {{- include "application.selectorLabels" . | nindent 6 }}
  securityGroups:
    groupIds:
      - {{ $securityGroupId }}
{{- end }}