apiVersion: v1
kind: Secret
metadata:
  name: {{ include "massdriver.fullname" . }}-kratos-envs
  labels:
    {{- include "massdriver.labels" . | nindent 4 }}
    app.kubernetes.io/component: kratos
data:
  COURIER_SMTP_CONNECTION_URI: {{ printf "smtp://%s:%s@%s:%s" .Values.smtp.username .Values.smtp.password .Values.smtp.hostname (toString .Values.smtp.port) | b64enc }}
  COURIER_SMTP_FROM_ADDRESS: {{ .Values.smtp.from | b64enc }}
  DSN: {{ printf "postgres://%s:%s@%s:%s/kratos?sslmode=require&max_conns=20&max_idle_conns=4" .Values.postgres.username .Values.postgres.password .Values.postgres.hostname (toString .Values.postgres.port) | b64enc }}
  SECRETS_COOKIE_0: {{ include "massdriver.kratos.cookie" . | b64enc | quote }}