apiVersion: v1
kind: Service
metadata:
  name: {{ include "massdriver.fullname" . }}-kratos
  labels:
    {{- include "massdriver.labels" . | nindent 4 }}
    app.kubernetes.io/component: kratos
spec:
  type: ClusterIP
  ports:
    - port: 4433
      targetPort: kratos-public
      protocol: TCP
      name: kratos-public
  selector:
    {{- include "massdriver.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: kratos
