image:
  repository:
  tag:

# k8s uses 'command' but Docker images call this ENTRYPOINT
# k8s uses 'args' but Docker images call this CMD
# both are commented out so the
# container ENTRYPOINT / CMD is used by default
# entrypoint: []
# cmd: []

envs: []
port:

serviceAccount:
  annotations: {}
  name:

resourceRequests: {}
resourceLimits: {}

replicaCount:
autoscaling:
  enabled: false
  minReplicas:
  maxReplicas:
  targetCPUUtilizationPercentage:

ingress:
  annotations: {}
  enabled: false
  className:
  host:
  path:

labels: {}

aws:
  securityGroup:
    enabled: false
    id:

# nodeSelector: {}

# tolerations: []

# affinity: {}


