image:
  repository:
  tag:

command: []
args: []

# specify your environment variables!
# default this is commented-out in case you don't have any
# envs: []
port:

serviceAccount:
  annotations: {}
  name:

resourceRequests: {}
resourceLimits: {}

replicaCount:
autoscaling:
  enabled: false
  minReplicas:
  maxReplicas:
  targetCPUUtilizationPercentage:

ingress:
  annotations: {}
  enabled: false
  className:
  host:
  path:

labels: {}

aws:
  securityGroup:
    enabled: false
    id:

# nodeSelector: {}

# tolerations: []

# affinity: {}


