concurrencyPolicy:
schedule:

completions:
parallelism:

image:
  repository:
  tag:

command: []
args: []

envs: []

serviceAccount:
  annotations: {}
  name:

resourceRequests: {}
resourceLimits: {}

labels: {}

aws:
  securityGroup:
    enabled: false
    id:

# nodeSelector: {}

# tolerations: []

# affinity: {}