apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "massdriver.fullname" . }}-launch-control
  labels:
    {{- include "massdriver.labels" . | nindent 4 }}
    app.kubernetes.io/component: launch-control
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "massdriver.fullname" . }}-launch-control
subjects:
- kind: ServiceAccount
  name: {{ include "massdriver.fullname" . }}-launch-control
  namespace: {{ .Release.Namespace }}