apiVersion: v1
kind: Service
metadata:
  name: {{ include "massdriver.fullname" . }}-launch-control
  labels:
    {{- include "massdriver.labels" . | nindent 4 }}
    app.kubernetes.io/component: launch-control
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.launchControl.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "massdriver.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: launch-control
