{{- if .Values.launchControl.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "massdriver.fullname" . }}-launch-control
  labels:
    {{- include "massdriver.labels" . | nindent 4 }}
    app.kubernetes.io/component: launch-control
  {{- with .Values.launchControl.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.launchControl.serviceAccount.automount }}
{{- end }}
